### ISSUE TITLE
Handling information that must always be revealed in a signature proof

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/bbs-signature#102]
One of the features of BBS signatures is the ability for the holder/prover to selectively disclose information they share with a verifier, which is a powerful feature. However, with this new feature comes new problems to solve. For example sometimes an issuer/signer of a token/credential using a BBS signature may want to ensure that a certain sub-set of the information protected by the signature is always revealed in a generated proof. An example might be the proof block in a LD-proof or the protected headers in a JWP. 

There are two main solution approaches that affect this spec that I think should be discussed:

1) Where the cryptographic layer is aware of this distinction in the two classes of information being signed (one class where that information must always be revealed in any generated proof, the other where that information is able to be selectively disclosed by the holder/prover) , note there is also some relevant commentary in #95 discussing this.
2) Where the cryptographic layer is essentially unaware of this distinction and it is left to the implementation layer above to enforce this behaviour if it so desires (e.g JWP or LD-Proofs)

The main tradeoffs I see here is increasing the complication of cryptographic layer for a potential increase in security of the scheme operating across application domains vs keeping the cryptographic layer simpler. Note - I use "potential" here deliberately as I haven't personally concluded whether there is a substantial security issue with the scheme in using 2) to achieve this outcome.

To bring things up a further level in option 1) the sign/verify API likely to be exposed by implementations is 

`signature = sign(privateKey, requiredRevealPayload, selectivelyDisclosablePayloads)`
`result = verify(publicKey, signature, requiredRevealPayload, selectivelyDisclosablePayloads)`

VS options 2) where the sign/verify API is likely to be exposed more like 

`signature = sign(privateKey, payloads)`
`result = verify(publicKey, signature, payloads)`

Technically with option 2) implementation layers using BBS in representation formats like JWP or LDP have to define within the bounds of their own specification if certain pieces of information MUST always be revealed. For example currently JWP using BBS defines that the first "payload" signed is the protected header. 

The potential risk I see with this model is a case when a signer is using a single key pair to sign JWP structures secured with a BBS signature AND sign payloads in other representation formats, in this threat a verifier could be handed a BBS proof revealing no payloads and be convinced it was signed under a different representation format than JWP. One could definitely argue that a signer/issuer operating in this manner is violating certain commonly agreed cryptographic best practises in failing to limit cross application key usage and therefore option 2) is fine to proceed with in this spec with an appropriate security consideration.

Interested to hear how other folks view this issue, in particular from spec editors involved in the development of representation layer technologies compatible with BBS signatures (e.g JWP or LD-Proofs) @quartzjer @selfissued @dwaite @OR13

**Comment by OR13** [comment]
This feels similar to crit in some ways. Given how frustrated some folks have been with alg none and crit in jose we should be cautious. 

My gut says to make it harder for an ignorant developer or verifier to make mistakes, which leads me to believe that the signatures should be aware of required and optional disclosure.

**Comment by quartzjer** [comment]
While it's traditionally higher level or application-space logic that enforces these kinds of requirements, similar to checking an issued-at or expiration... I think it's worth strongly considering having this capability in the crypto layer whenever feasible.

The tradeoff or caveat though is if the added complexity creates *any* higher possibility of a vulnerability, it's much better to deal with that when it happens in implementations (2) vs. in the algorithm itself (1).

The challenge in general with this space where BBS/JWP/LDP/etc live is that to build privacy preserving cryptographic primitives some of this logic _must_ be moved into the algorithms, and the complexity can't just be pushed up the stack.

So, sort of thinking out loud here...
1. BBS is optimized for use-cases involving unlinkability
2. The nothing-disclosed case is definitely a notable security consideration (but still could be a valid use-case)
3. Most or nearly all issuers will want something required to be revealed
4. If the location of the required payload is not uniform in every signature it becomes a linkability vector
5. Adding requiredRevealPayload does not invalidate the nothing-disclosed use case (it can just be empty)
6. The added algorithmic complexity to support it is minimal (in my limited understanding)

I'm in favor of (1), having the algorithm natively support it.  The slightly larger calling syntax helps ensure that all implementations prioritize the distinction of what is required vs selectively disclosed, and it also provides a means for requiring disclosure that doesn't potentially introduce linkability when solved elsewhere.

**Comment by tplooker** [comment]
This issue was discussed on the WG call this morning where it was agreed that PR #95 would be updated to accomodate this change, I will tag this issue with "ready-for-pr" because of this pending close subject to that PR being merged

**Comment by tmarkovski** [comment]
What checks will the routine in `sign` and `verify` do to validate if the `requiredRevealPayload` is satisfied? If it does a simple array comparison of indexes, it doesn't make sense to add this protection on the signature suite spec level.
The sign/verify method shouldn't be opinionated, unless that's required for the cryptographic construction of the signature. I understand that most use cases will want this, we're still thinking within the frames of how we currently use them.
I think I must be missing something (other than the last WG meeting), since everyone is in favor of adding this protection, which seems like an obvious architectural anti-pattern to me.

**Comment by andrewwhitehead** [comment]
@tmarkovski The requiredRevealPayload is incorporated into the hash for the DST message, along with other public parameters required for the security of the signature, like the issuer's public key. Unlike the other signature messages, this one cannot be selectively revealed, and so it would not be possible to verify a signature or a proof of knowledge without knowing the correct value for requiredRevealPayload.

The spec doesn't define a format for the requiredRevealPayload beyond it being represented as a byte string, but applications can use it to enforce agreement for any additional parameters. I'm curious what makes this look like an anti-pattern to you, but I would recommend listening to the meeting recording.

**Comment by tmarkovski** [comment]
Thanks for clarifying the use of it. My next question was why not allow any payload to participate in the DST message to allow extensions for it, but you answered that in the second paragraph. Which brings me to my next question: why is this parameter named `requiredRevealPayload` if it will allow arbitrary data by the application?

My thoughts on anti-pattern stem from the idea of using knowledge of downstream application into the spec, without making use of it. Example: requiring parameter for which messages are required for an application protocol is a downstream problem. However, parameter for integrity payload is a generalized use. While both cases will be defined by applications, one is opinionated about what it is, the other one isn't.

**Comment by andrewwhitehead** [comment]
We're still workshopping the naming, I think 'header' is in the lead at the moment although every term comes with its own baggage.

**Comment by tplooker** [comment]
@tmarkovski essentially the conversation on the WG call yesterday and in the DIF slack channel appears to have shown support to have a cryptographically enforce-able way to support two types of information protected by a signature 

1) Header - Data protected by the original signature that must be revealed in any generated proof for the signature
2) Payloads - An array of payloads protected by the original signature of which the holder/prover has the ability to selectively disclose

Those are the current names anyway, if you have alternatives please feel free to suggest.

**Comment by tplooker** [comment]
Or of course if you have a different take on the usefulness of this feature please feel free to share :)

**Comment by tmarkovski** [comment]
I've no objections (or suggestions) on the naming or the usefulness of this feature. By reading the OP description (and not having much more context), I made an assumption that the `requiredRevealPayload` refers to required message indices that applications need disclosed, which seemed like a very specific, opinionated application argument that shouldn't have place in these algorithms directly. As @andrewwhitehead explained, this parameter is a general header payload defined as public parameter by applications, which may contain information about what message indices may be required, in addition to other info. This makes a lot more sense and clears up my confusion.

**Comment by tplooker** [comment]
Address via #95
