### ISSUE TITLE
Add generator in G1 in BlindSign

### ISSUE THREAD

**Issue by alessandroguggino** [decentralized-identity/bbs-signature#107]
From the BlindSign function:
https://github.com/decentralized-identity/bbs-signature/blob/506d70c0d266a3b04cb8e8a58796008d5284fd2e/draft-blind-bbs-signatures.md?plain=1#L175

We should add P1, the generator point in G1, in order to make a valid signature after the unblinding:
`
b = commitment + P1 + h0 * s'' + h[j1] * msg[1] + ... + h[jK] * msg[K]
`

If you agree with me I will open a pull request where I will change `b` as proposed and add P1's definition into the Terminology section.

**Comment by BasileiosKal** [comment]
Yeap! That make sense to me.

**Comment by alessandroguggino** [comment]
I have seen that in the main draft P1 is defined in Notation instead of Terminology. But there is no Notation section. May I add it and modify the structure of the document following the one of the main draft?
This is related to issue #90. 
Otherwise, I just change the calculation of b for now.

**Comment by tplooker** [comment]
Yes @alessandroguggino as documented in #90 feel free to update it for consistency. I would suggest instead of duplicating the terminology you could just reference the core draft?
