### ISSUE TITLE
Ciphersuites format

### ISSUE THREAD

**Issue by BasileiosKal** [decentralized-identity/bbs-signature#118]
The ciphersuites definition currently used in the spec needs to be updated.
1. There are terms that must be defined by most likely referencing their definition to some other spec. Examples include the base points of G1 and G2, the prime order p of those groups the security level of the ciphersuite (`k` in PR #116). Are there any other definitions we should include??
2. A specific format for the ID of each ciphersuite must also be defined. Something like,
```
Cipher_ID = "BBS_" || H2C_SUITE_ID || GEN_SC || HASH_OUTPUT_LEN || _"
```
where `GEN_SC` will be used to distinguish between the scopes of the generators seed (i.e., global or issuer specific) and `HASH_OUTPUT_LEN` between the number of bytes drawn for each XOF (since the consensus seems to be that we will parameterize that value)??

**Comment by tplooker** [comment]
Discussed on WG call 15th of August, issue has been resolved through #137
