### ISSUE TITLE
Reference/Spec Implementation Language/Framework Selection

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/bbs-signature#119]
As resolved earlier this year multiple WG members expressed support for there to be a prototypical style implementation housed within this repo to test the implementability of the spec.

There are multiple possible languages/frameworks we could use, below is a bit of a list including key libraries we could use

- Rust using https://docs.rs/bls12_381/latest/bls12_381/
- Python using https://github.com/zebra-lucky/python-bls
- Javascript using https://github.com/paulmillr/noble-bls12-381

**Comment by christianpaquin** [comment]
Ok, time to stop procrastinating and start carving out time for this. I'll volunteer to implement a JavaScript one, since that's my most recently used language.

**Comment by tplooker** [comment]
Thanks @christianpaquin really appreciate you taking the pen here!

**Comment by tplooker** [comment]
Discussed on WG call 15th of August, implementations by multiple WG members ongoing
