### ISSUE TITLE
H_s and H_d not defined in BLS ciphersuite

### ISSUE THREAD

**Issue by christianpaquin** [decentralized-identity/bbs-signature#139]
The terminology section says that the `H_s` and `H_d` generators are defined by each ciphersuite, but they are not defined in the BLS12-381 Ciphersuite section.

**Comment by tplooker** [comment]
Agree this is confusing, currently we have `blind_value_generator_seed` and `signature_dst_generator_seed` which are intended to be used with the [CreateGenerators](https://identity.foundation/bbs-signature/draft-bbs-signatures.html#name-creategenerators) operation to derive H_s and H_d, but this needs to be clarified further
