### ISSUE TITLE
Generators ordering

### ISSUE THREAD

**Issue by BasileiosKal** [decentralized-identity/bbs-signature#141]
It would be very useful to have a clear way to define the order of the generators in the draft. This would allow us to naturally also define the order of the signed messages that it is also needed.

Two options as far as I know are:
1. Based on their index (i.e., the order of which they are created). So, H_1 will be the first generator created, H_2 the second etc.
2. Based on their value (using some metric, maybe Euclidian distance??, or alphabetically using their octet representation??).

IMO 2 seems to be a fair amount more complicated. 

On the other hand, using 1, to validate that some generators have the correct "order" one will have to re-create them. 

For that reason, I tent more in the second option, but I do recognize that both have trade-offs.

**Comment by tplooker** [comment]
@BasileiosKal is this issue resolved now?

**Comment by BasileiosKal** [comment]
Yes! The spec moved with option 1 from above. Closing.

If there is other practical issues with the generators ordering in the cache, those will be better discussed in another issue.
