### ISSUE TITLE
H2C using SHA256

### ISSUE THREAD

**Issue by BasileiosKal** [decentralized-identity/bbs-signature#143]
Currently the spec creates generators using hash-to-curve implemented with `shake256` (for which we describe a h2c ciphersuite).

Looking at implementations of pairing-friendly-curves though, most of them seem to natively support h2c with `sha256` (like blst). This means that,
1. We may have to implement h2c with `shake256` our self's.
2. Applications that elect to use the natively supported h2c implementation (and will be many of those most likely) will create generators that are not interoperable with the ones we describe in the spec.

At the very least we may be creating an implementation barrier by making it hard to use `sha256` for h2c.

Since efficiency is not an issue when creating generators, and taking into account the wider spread of `sha256`, should we update h2c to use `sha` instead of `shake`?? We can leave the ciphersuite definition for h2c using `shake256` as an alternative, while the bls12-381 ciphersuite will use h2c with `sha256`??

**Comment by BasileiosKal** [comment]
@christianpaquin was this your experience as well with the javascript libraries?? 

c.c. @tplooker, @andrewwhitehead, @mikelodder7 ^^

**Comment by mikelodder7** [comment]
JavaScript libraries have shake/SHA3 available to them but will have to implement h2c. I think h2c is more of a barrier than SHAKE.

**Comment by christianpaquin** [comment]
> @christianpaquin was this your experience as well with the javascript libraries??

I'm using the [noble-bls12-381](https://github.com/paulmillr/noble-bls12-381.git) library, which supports hash-to-the-BLS curve, but I haven't confirmed if it's the same as we specified. The hash-to-curve spec [BLS suites](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-hash-to-curve-14#section-8.8) use SHA-256, so I'd prefer using that. I know we had a discussion of using SHA vs SHAKE in the past, but I'd advocate to using the simple hash function whenever possible, because it should always be available in libraries (or environments) providing shake.

**Comment by mikelodder7** [comment]
I’ve had to implement h2c in multiple languages and each language already had shake: Go, Rust, Java to name a few. My point is Shake was already available and h2c was not. H2c is the more limiting factor I have found not the other way around

**Comment by mikelodder7** [comment]
The other problem I have with SHA2 Is its vulnerable to extension attacks. Implementers don’t even think about that. This is why we have HMac & HKDF. By staying with SHA3 algorithms, implementors do not have to worry about that

**Comment by tplooker** [comment]
> I’ve had to implement h2c in multiple languages and each language already had shake: Go, Rust, Java to name a few. My point is Shake was already available and h2c was not. H2c is the more limiting factor I have found not the other way around

I think the point is, how many of these languages had H2C implementations but just not for XOFs? Because if H2C w SHA-256 exists in most languages then shifting to this variation would have a meaningful impact on implementation complexity

**Comment by tplooker** [comment]
I think its safe to assume that there are more H2C implementations w SHA-256 then there is XOF based purely on the fact that popular signature schemes like BLS signatures depends on it

**Comment by tplooker** [comment]
> I'm using the [noble-bls12-381](https://github.com/paulmillr/noble-bls12-381.git) library, which supports hash-to-the-BLS curve, but I haven't confirmed if it's the same as we specified. The hash-to-curve spec [BLS suites](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-hash-to-curve-14#section-8.8) use SHA-256, so I'd prefer using that. I know we had a discussion of using SHA vs SHAKE in the past, but I'd advocate to using the simple hash function whenever possible, because it should always be available in libraries (or environments) providing shake.

As an example [see here](https://github.com/paulmillr/noble-bls12-381/blob/main/math.ts#L1098) looks like this library only supports the SWU variation of H2C rather than the XOF based one. [blst](https://github.com/supranational/blst) as a library is similar.

**Comment by mikelodder7** [comment]
Swu has nothing to do with the hash function. To be clear it’s the expand_msg vs expand_xof. That’s the only difference

**Comment by mikelodder7** [comment]
What you want is here https://github.com/paulmillr/noble-bls12-381/blob/main/index.ts#L236

**Comment by mikelodder7** [comment]
The difference is quite small. You use expand_xof vs expand_msg, expand_xof is less code and faster to compute. I don’t think this as big of a barrier as you are thinking it will be

**Comment by tplooker** [comment]
>  Swu has nothing to do with the hash function. To be clear it’s the expand_msg vs expand_xof. That’s the only difference

Quite right, my apologies.

**Comment by BasileiosKal** [comment]
In the end i think we are in agreement here. I agree that a big barrier may be h2c but even in libs that have h2c implemented, a lot of times it will be with just a hash (like [noble-bls12-381](https://github.com/paulmillr/noble-bls12-381/blob/b55eca3ae0f2f1cb35d768cd432ca3f57d26a47a/index.ts#L278) and [blst](https://github.com/supranational/blst/blob/master/src/hash_to_field.c#L139)). This makes sense since most of them target bls-sigs. So IMO it's the combination of the two that makes things difficult and not just h2c.

**Comment by andrewwhitehead** [comment]
If we have global message generators then libraries can just use cached values (up to a maximum message count) and might not have to implement H2C depending on the application.

**Comment by BasileiosKal** [comment]
Merging #177 and #151 made it possible to define a bbs ciphersuite with only one hash function in the basis of a (single) H2C suite. This addresses this issue. Will close after the next call.

**Comment by BasileiosKal** [comment]
Discussed in the 2022-07-04 WG call! Will leave open until we decide if we will define a second sha256 based ciphersuite in the spec.

**Comment by tplooker** [comment]
Discussed on 8th of August WG call there appears to be a meaningful improvement in the implementability of the scheme when using SHA256 based on pre-existing implementations. Therefore we see value in defining a cipher suite to work with SHA256. The question remains on whether this is an additional cipher suite OR a replacement for the current one that uses SHAKE 256.

**Comment by tplooker** [comment]
DIscussed on 15th of August WG call, based on implementation feedback we are going to define a SHA256 based ciphersuite to support further discussion around it.

**Comment by tplooker** [comment]
Resolved in #213
