### ISSUE TITLE
Clarify point serialization

### ISSUE THREAD

**Issue by christianpaquin** [decentralized-identity/bbs-signature#146]
The ciphersuite's `octets_to_point` is ambiguous, as it is unclear which point type should be returned (from G1 or G2). This can be inferred by cross-referencing other parts of the spec, but implementers would benefit from a clearer description; e.g., either adding a `_g1` of `_g2` suffix to the method or a type input. The BLS spec support two modes (where G1 and G2 are swapped), so the ambiguity is by design; BBS fixed the group, so we don't need to keep the BLS notation. `point_to_octects` is not as problematic, since presumably you can infer the input type, but we should harmonize both function names.

Another clarification question: both `point_to_octets` and `octets_to_point` refer to the CRFG pairing-friendly curves spec's Appendix C, but doesn't mention which mode to use (compressed or not).  As an example, the BLS spec uses compressed serialization (see its [Appendix A](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-bls-signature-04#appendix-A))

**Comment by BasileiosKal** [comment]
I may be missing something but isn’t it possible to determine if the point should be in G1 or G2 by the encoded to octets value of the point itself, based on the length of that value (called s_string in the [pairing-friendly-curves spec](https://www.ietf.org/archive/id/draft-irtf-cfrg-pairing-friendly-curves-10.html#name-zcash-serialization-format-)). The same holds for compression vs non-compression case that can be determined by the C_bit defined [here](https://www.ietf.org/archive/id/draft-irtf-cfrg-pairing-friendly-curves-10.html#name-point-serialization-procedu).

If I’m not missing something and the proposal is to add the `_g1` and `_g2` suffixes to increase readability but have the operations essentially be the same in both cases I’m all for it.

**Comment by christianpaquin** [comment]
Yes, I think adding `_g1` and `_g2` would be the simplest solution. Maybe there are ways to figure out what needs to be done, but for devs calling a 3rd party BLS library (like me), it's not immediately clear which function to call (having to consciously recall which group if for pub keys and generators). Moreover, future ciphersuites might have different rules, so an explicit target group removes potential ambiguity.
