### ISSUE TITLE
Generalize the presentation proof nonce

### ISSUE THREAD

**Issue by christianpaquin** [decentralized-identity/bbs-signature#15]
The spec currently specifies a presentation nonce to prevent replay attack, and recommends it to be a random value. I suggest we had a few details and requirements around nonce generation, to accommodate various scenarios: 
 - For replay protections, the nonce only need to be unique, so a verifier identifier + timestamp would work (to create proofs non-interactively).
 - If the holder keys are held in hardware that the user only has access for a limited period of time, then making the nonce random prevents the user pre-generating proofs to be used later after the authorized period.
 - A BBS+ attribute credential can be used to create a digital signature on some data, disclosing a subset of the attributes. In this case, the nonce can be the digest of the signed data.

I can create a PR with suggested updates.

**Comment by BasileiosKal** [comment]
I agree with defining requirements around nonce generation. I don’t understand though how the third option prevents replay attacks or pre-generated proofs (could not the adversary replay the presentation of the same disclosed attributes or pre-generate proofs for the whole credential??). I would appreciate if you could explain that part.

**Comment by christianpaquin** [comment]
The last point is a different potential use case: digital signature on say, a document, vs. using a BBS+ credential for authn/authz. E.g., Jane is a professional engineer of company A is asked to review and sign off on the design of a project from company B. She does, and uses her work credential with attributes (name, affiliation, level, role, etc.) to sign off the document, and discloses affiliation, level, and role (e.g., "This was signed by a level 60 engineer from the Cloud group of Company A"); she does not disclose her name because her company doesn't want the customer to poach their employees. In this case, the challenge `c` is the hash of the document, just like in conventional electronic signatures. There isn't a replay attack in this case; since the attacker would simply present the same signed document with same signature and disclosed attributes.

**Comment by BasileiosKal** [comment]
Thank you for the explanation. I think it’s a very interesting use-case and it would be great to have it documented in the spec. 

Maybe we should also include the proof purpose to the nonce to avoid an un-trusted verifier getting documents signed by supplying the hashes of the documents as random nonces (in an interactive protocol)??

**Comment by BasileiosKal** [comment]
As a follow up to that issue, after talking with @christianpaquin I realized I had misunderstood the proposed use case. Although there could be a higher layer spec defining credentials for signing documents, I think it would be nice to also have that use case documented in the current spec and recommend a nonce accordingly (Maybe add a nonce generation section in the security considerations??).

**Comment by tplooker** [comment]
Addressed in PR #55, closing on that basis
