### ISSUE TITLE
Integer endianness

### ISSUE THREAD

**Issue by BasileiosKal** [decentralized-identity/bbs-signature#157]
As noted by @mikelodder7,  in the document we don't yet discuss the integers (i.e., scalars mod r) serialization. More specifically, since we have a description for the byte length of those integers (`octet_scalar_length`), what is missing is the byte order.

In general i thing little-endian is preferred (it is mostly used in bls libs like the rust crate and blst) but an issue is that I2OSP uses big-endian if im not mistaken.

There are 3 options i can think of;
1. We describe them as 32 bytes (or `octet_scalar_length` in general) in little-endian, with a note for I2OSP.
2. We describe them in a way similar to some libs (i.e., four 64 bit parts in little-endian order), but i don't think something like that is suitable. 
3. We leave it up for implementers with some notes for guidance.

At the moment I'm leaning more towards option 3. Implementations may elect to use any kind of optimization and this will allow for that. 

Also for what i know of, other specs like ecdsa and eddsa elect to define the integer's endianness but specs like bls-sigs and h2c adopt option 3, so it does not seem to be any "absolutely correct" way to do that.

**Comment by dev0x1** [comment]
@BasileiosKal May be we can also update to use consistent ordering of **Abar** and **A'** in proof and input to `hash_to_scalar`, 
in `ProofGen`,
`19. c = hash_to_scalar((PK || Abar || A' || D || C1 || C2 || ph), 1)`

`25. proof = (A', Abar, D, c, e^, r2^, r3^, s^, (m^_j1, ..., m^_jU))`

in `ProofVerify`,

`4. (A', Abar, D, c, e^, r2^, r3^, s^, (m^_j1,...,m^_jU)) = proof`

`10. cv = hash_to_scalar((PK || Abar || A' || D || C1 || C2 || ph), 1)`

**Comment by tplooker** [comment]
Discussed on WG call 8th of august, there is currently ambiguity around the endianness of scalar_to_octets that needs to be resolved.

**Comment by tmarkovski** [comment]
I ran into this issue as I was going through spec implementation and validating against the provided fixtures. Has there been a decision made? I think at minimum, the fixtures should specify the byte order of the scalar.

**Comment by mikelodder7** [comment]
If we give the actual bytes then little endian is preferable

**Comment by tmarkovski** [comment]
> If we give the actual bytes then little endian is preferable

The `SignatureToOctets` does give the actual bytes and for scalars it refers to `i2osp` which specifies them as big-endian. Do you propose that we use little-endian instead for the signature and proof composition?

**Comment by tplooker** [comment]
Related to updates in #221
