### ISSUE TITLE
API Update

### ISSUE THREAD

**Issue by BasileiosKal** [decentralized-identity/bbs-signature#159]
Trying to update the API has resulted in mainly two proposals from @andrewwhitehead and @tplooker. The first one using boolean variables to distinquish between revealed and un-revealed messages and the second one using indexes. You can compare the 2 APIs [here](https://github.com/BasileiosKal/dif-bbs-signature-api):
- [API_1](https://github.com/BasileiosKal/dif-bbs-signature-api/tree/main/API_1_Boolean) (using Booleans): [Sign](https://github.com/BasileiosKal/dif-bbs-signature-api/blob/main/API_1_Boolean/draft-bbs-signatures.md#sign), [Verify](https://github.com/BasileiosKal/dif-bbs-signature-api/blob/main/API_1_Boolean/draft-bbs-signatures.md#verify), [ProofGen](https://github.com/BasileiosKal/dif-bbs-signature-api/blob/main/API_1_Boolean/draft-bbs-signatures.md#proofgen), [ProofVerify](https://github.com/BasileiosKal/dif-bbs-signature-api/blob/main/API_1_Boolean/draft-bbs-signatures.md#proofverify)
- [API_2 ](https://github.com/BasileiosKal/dif-bbs-signature-api/tree/main/API_2_Indexes)(using Indexes): [Sign](https://github.com/BasileiosKal/dif-bbs-signature-api/blob/main/API_2_Indexes/draft-bbs-signatures.md#sign), [Verify](https://github.com/BasileiosKal/dif-bbs-signature-api/blob/main/API_2_Indexes/draft-bbs-signatures.md#verify), [ProofGen](https://github.com/BasileiosKal/dif-bbs-signature-api/blob/main/API_2_Indexes/draft-bbs-signatures.md#proofgen), [ProofVerify](https://github.com/BasileiosKal/dif-bbs-signature-api/blob/main/API_2_Indexes/draft-bbs-signatures.md#proofverify)

We can somewhat compare the two APIs based on the total number of lines (i.e., everything inside each code block) and the total number of procedure steps,

### API 1 (Booleans)

|                  |  lines   | Procedure Steps | 
| ----------- | ------ | ----------------- | 
| Sign           |   54    |        9                   | 
| Verify         |  59     |       11                  | 
| ProofGen   |  109   |       26                  | 
| ProofVerify |   78    |       14                  | 

### API 2 (Indexes)

|                   | lines | Procedure Steps |
| ----------   | ---- | ----------------- |
| Sign           |  55  |   10                     |
| Verify         |  59  |   12                     |
| ProofGen   | 101 |    29                    |
| ProofVerify | 81   |   18                     |

We can see that there is not much difference between the two or a clear winner. Procedures in API 2 have more steps but the total lines are about the same. So, the choice should be made based on which one is more readable and more tolerant to implementation mistakes.

### Note:
When using API 2 there may be more checks to be done when it comes to the indexes i.e., that are truly between 1 and L. Right now this is only described above the operations. It is important though, especially in `ProofVerify`. 

For example, if not checked, the prover could reveal an extra message with an "invalid" index (like `index = L+1`), and the proof may validate depending on the implementation. So more steps may be needed in `ProofVerify` to make this check explicit.

Currently PR #138 proposes the use of API 2. Personally i find that it is a little more clear overall especially when it comes to the ordering of the input lists (see also #117 for some context).

**Comment by tplooker** [comment]
Labeling as pending close ahead of WG call on the 4th of july

**Comment by tplooker** [comment]
Discussed on july 4th WG call resolved via #183
