### ISSUE TITLE
Blinded signatures revision

### ISSUE THREAD

**Issue by BasileiosKal** [decentralized-identity/bbs-signature#16]
As it is right now, the commitment mechanic (blinded signatures) could lead to some inconsistencies and possible forged signatures. For example, if the Issuer signs the messages `m1`, `m2`, a "standard" (non-blinded) signature would be, `(A, e, s)` with

    A = (g0 + h0 * s + h1 * m1 + h2 * m2)*(1/(SK+e))

If the Holder commits a message `m3` using `h1`, i.e., 

    commit = h0 * s’ + h1 * m3

The blinded signature, created by the Issuer, would be 

    A_blind = (commit + g0 + h0 * s + h1 * m1 + h2 * m2)*(1/(SK+e)) = 
      = (g0 + h0 * (s+s’) + h1 * (m1+m3) + h2 * m2) * (1/(SK+e)). 

Notice that `(A_blind, s+s’, e)` is a valid BBS+ signature in the messages `(m1+m3)` and `m2`, which is not the desired outcome and a potential forgery (`A_blind`, `s`, `s’` and `e` are known to the Holder). 

The main problem is that currently there is no mechanism for the Issuer to validate that the Holder does not create commitments using the same G2 elements as themself (`h1` in the example above). My proposal is (at least for now) to define a blinded signature that would only contain committed from the Holder messages.

**Comment by andrewwhitehead** [comment]
This is exactly why the commitment proof of knowledge needs to be verified by the issuer prior to creating a signature using the commitment.

**Comment by BasileiosKal** [comment]
Thank you for your answer. I had misunderstood BlindMessagesProofGen. I think we should also mention that the Issuer should check that the used generators for the commitment are not also used for the signature, (i don't think it would be obvious to an implementer). I can make a pr for that and i think we can close this issue.
