### ISSUE TITLE
Structured vs de-structured inputs

### ISSUE THREAD

**Issue by BasileiosKal** [decentralized-identity/bbs-signature#163]
Lately the direction the document is going, is to pass inputs in a structured form (i.e., `octets_to_signature(signature)` vs `octets_to_signature(A, e, s)` etc.). Related to #138 and #155.

Opening the issue so we can keep track of the update and make notation consistent across the spec.

**Comment by tplooker** [comment]
Im comfortable with passing structured inputs as the convention, I think we should also denote the destructing syntax in the terminology section though e.g (a,b,c) = arg and what it means for clarity
