### ISSUE TITLE
Defintions of P1 and P2 in Ciphersuites

### ISSUE THREAD

**Issue by dev0x1** [decentralized-identity/bbs-signature#164]
Since any point on respective cyclic subgroup G1 and G2 can work as P1 and P2.
For interoperability, I think we should define the values of P1 and P2 in cipher suites. By clubbing this value in ciphersuite, an interoperable implementation has to refer only to cipher suite ID otherwise these have to be communicated on application-level messages or protocols.

Regarding values for BLS12-381 ciphersuites, fixed base generators defined by pairing-crypto libraries zkcrypto(defined [here](https://github.com/zkcrypto/bls12_381/blob/34dab74ae44cd77dfa867928dd2e6c8383d8dc9d/src/g1.rs#L198) and [here](https://github.com/zkcrypto/bls12_381/blob/34dab74ae44cd77dfa867928dd2e6c8383d8dc9d/src/g2.rs#L212)) and blst(defined [here](https://github.com/supranational/blst/blob/bd8e64f97cb55217df1f7e84d4d73d6d8461e608/src/e1.c#L20) and [here](https://github.com/supranational/blst/blob/bd8e64f97cb55217df1f7e84d4d73d6d8461e608/src/e2.c#L24)) can be used. Both these libraries use same value for fixed base generators.

**Comment by BasileiosKal** [comment]
Thanks for raising! This will be very useful to track the issue! I think the (unfortunately **implicit**) assumption is that P1 and P2 will be the base points from the [pairing-friendly curves](https://www.ietf.org/archive/id/draft-irtf-cfrg-pairing-friendly-curves-10.html) spec (that are also used by the libs listed). There are some discussions to maybe use different points though (see #37).

Another option could be to go the [bls-signatures](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-bls-signature-04#appendix-A) route and (re-)define the "curve suite" in an appendix (really just a mapping between terms). If we decide then to use different base points the update will be very easy.

**Comment by tplooker** [comment]
Discussed on 8th August WG call, we need to explicitly call out P1 and P2 in the cipher suite to resolve this ambiguity.

**Comment by tplooker** [comment]
Options discussed are 

1. Document P1 and P2 as the base points on the underlying curve
2. Document P2 as the base point on the underlying curve and select a single new global (per-curve) value for P1 to preserve the usage of the base point in G1 for private holder binding
3. Use the create generator procedure to output Q1 as P1

**Comment by tplooker** [comment]
Discussed on WG call 17th of October, closing with merge of #215
