### ISSUE TITLE
Uncompressed points data in hash_to_scalar input

### ISSUE THREAD

**Issue by dev0x1** [decentralized-identity/bbs-signature#166]
`hash_to_scalar` in different procedures accepts concatenation of G1 Points(`PK`, `A_bar`, `A_prime` or `D`) to be given as input. For Bls12-381 based cipher suites, the `point_to_octets_in_g1` method refers Zcash-serialization method as defined [here](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-pairing-friendly-curves-10#appendix-C), which specifies points can have compressed and uncompressed form of representation. For network transmission and storage, a compressed form is desired but was wondering for input to the hash function, if providing extra data from the uncompressed points can give more randomness and beneficial in this case in any way.

**Comment by BasileiosKal** [comment]
That would be definitely nice. Thank you for the suggestion!

I'm not 100% convinced that the raised complexity will be worth it though. the additional data passed into the hash will be deterministically defined by what is already inputted (the compressed version). So they will not help with brute force attacks etc., or provide much more entropy.

**Comment by dev0x1** [comment]
Thanks for your feedback. I had an impression that while encoding for the compressed form there would be few deterministic metadata bits that will be absent in uncompressed form but this is not the case. Now I get that to keep things simple, using only compressed representation works very well.

**Comment by BasileiosKal** [comment]
Great! Closing the issue since we reached a consensus! (@dev0x1 please re-open if that's not accurate or you feel there's more to discuss)
