### ISSUE TITLE
Explicitly give the number of bytes for the PRF function

### ISSUE THREAD

**Issue by christianpaquin** [decentralized-identity/bbs-signature#168]
The PRF function in `ProofGen` takes the value `8*ceil(log2(r))`. It would be helpful to explicitly define its value for the BLS12-381 ciphersuite to avoid guess work. I assume the value is 256.

**Comment by tplooker** [comment]
Suggestion discussed on WG call is to generalize the `xof_no_of_bytes` parameter for this purpose and parameterize it in the proof gen procedure.
