### ISSUE TITLE
expand_message domain separation

### ISSUE THREAD

**Issue by BasileiosKal** [decentralized-identity/bbs-signature#194]
The current hash_to_scalar construction does not allow for the calling operation to define the DST that will go into the underlying expand_message used. Some operations that need additional domain separation append the DST to the message.

The problem is that we cannot prove indistinguishably that way. For example consider the following, lets assume that in a protocol we call hash_to_scalar in the input `msg ||  I2OSP(length(DST2), 1) || DST2` and get `b_1, b_2, ...` where,

```
b_0 = H(Z_pad || msg ||  I2OSP(length(DST2), 1) || DST2 || I2OSP(len_in_bytes, 2) || I2OSP(0, 1) || DST_prime)
b_1 = H(b_0 || ...)
b_2 = ....
```
Then, in some other place, the protocol returns `h2 = H(Z_pad || msg || I2OSP(length(DST2), 1) || DST2)`. In that case, after observing `h2` I could do a length-extension attack on H, calculate `b_0` and then `b_1`, `b_2` etc. This is not really a practical issue (it becomes less practical -but not impossible- if we also consider padding), but it does stop us from proving security. It also becomes a larger issue if people use a different expand_message (if they just use sha512 with a counter for example).

### Solution A
The currently proposed solution, discussed in the WG call, would be to define an additional optional argument to hash_to_scalar like `dstInfo` and append that to the DST already defined. i.e., inside hash_to_scalar calculate,
```
4. dst_prime = DST || dstInfo || I2OSP(length(dstInfo), 1)
5. expand_message(msg, dst_prime, len_in_bytes)
```
This is a bit weird because we are prepending the length everywhere else in the spec. However, if we do the same here and calculate `dst_prime = DST || I2SOP(length(dstIfo), 1) || dstInfo` then for example the pairs `DST1 = [4, 2]`, `dstInfo1 = [2]` and `DST2 = [4]`, `dstInfo2 = [1, 2]` will give the same `dst_prime`. 

Similarly, we can't just concatenate the 2 (i.e., `dst_prime = DST || dstInfo`) because then for example the pairs `DST1 = [1, 2]`, `dstInfo1 = [3]` and `DST2 = [1]`, `dstInfo2 = [2, 3]` will again give the same `dst_prime`

### Solution B
Don't define the DST in hash_to_scalar but require it as an input. So whatever operation calls hash_to_scalar will also need to specify a DST value to pass it. This is probably the most efficient approach when it comes to a straight line implementation, but IMO the "ugliest" looking when it comes to the spec.

**Comment by BasileiosKal** [comment]
Also, @andrewwhitehead pointed out that the only place that this method of domain separation (i.e., appending the dst to the msg) is currently used, is in [MapMessageToScalarAsHash](https://identity.foundation/bbs-signature/draft-bbs-signatures.html#name-mapmessagetoscalarashash). That said, it will be a useful thing to resolve in general (see for example PR #186).

Also for completeness, another solution (that I'm not a huge fan of) is the following:
### Solution C
Append the length of both the DST and the dstInfo to create dst_prime, i.e., inside hash_to_scalar do, 
```
4. dst_prime = I2OSP(length(DST), 1) || DST  || I2OSP(length(dstInfo), 1) || dstInfo
5. expand_message(msg, dst_prime, len_in_bytes)
```
This is more consistent with the rest of the spec but it is a bit wasteful since, if `dstInfo` is not supplied, we will be prepending the `DST` with its length twice (once outside and once inside `expand_message`).

**Comment by andrewwhitehead** [comment]
I think a third option is just to add an optional `dst` parameter to `hash_to_scalar`, defaulting to (something like) `BBS_ || ciphersuite_id || HASH_TO_SCALAR`. Then `MapMessageToScalarAsHash` is just `hash_to_scalar` with a DST like `BBS_ || ciphersuite_id || MESSAGE`, and KeyGen could use another DST (with key_info added). Existing uses of `hash_to_scalar` wouldn't need to be updated.

**Comment by BasileiosKal** [comment]
That may be the best solution. I'm not 100% clear as to how a calling operation like MapMessageToScalarAsHash will define the dst for hash_to_scalar?? Will hash_to_scalar be a parameter for that operation and define the dst there?? i.e., something like,
```
result = MapMessageToScalarAsHash(msg)

Parameters:

- hash_to_scalar, the hash_to_scalar operation defined in (#hash-to-scalar) with the dst parameter set
                  to "BBS_ || ciphersuite_id || MESSAGE"
```
Maybe an easiest option will be to define the dst in hash_to_scalar as an optional input that defaults to `BBS_ || ciphersuite_id || HASH_TO_SCALAR` rather than an optional parameter that does the same?? Or is this more error prone??

**Comment by andrewwhitehead** [comment]
^ Yes, I meant input, not parameter.

**Comment by BasileiosKal** [comment]
Cool! Yea this maybe the best thing to do. I think it is a little more prone to error but that is why we have test vectors. Will give it a shot!

**Comment by tplooker** [comment]
Discussed on WG call on 15th August, issue is ready for PR with consensus to move forward with the approach described by @andrewwhitehead
