### ISSUE TITLE
Document the binary formats for cryptographic structures defined by the specification

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/bbs-signature#2]
Within the draft there are several new cryptographic structures that are encoded in binary, their format should be documented to support interoperable implementations, these include

- ProofOfKnowledge (signature proof)
- Commitment
- Commitment ProofOfKnowledge
- BBS Signature

**Comment by tplooker** [comment]
@andrewwhitehead

**Comment by tplooker** [comment]
A topic for future discussion is whether to use a structured (e.g CBOR) vs custom binary format, current implementations use a custom binary format however structured solutions like CBOR could be considered for future revisions.

**Comment by ChristopherA** [comment]
I’m hoping you document CBOR versions of these (and not the IPFS version of CBOR). We are increasingly using CBOR in wallet interoperability standards as it allows airgap solutions like UR: 

* https://github.com/BlockchainCommons/crypto-commons#urs
* https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-005-ur.md

**Comment by tplooker** [comment]
#66 adds a preliminary serialisation format for the signature, however the proof representation is still un-documented

**Comment by tplooker** [comment]
Signatures have been addressed in #66 only outstanding rules are for proofs therefore closing this issue in favour of #153
