### ISSUE TITLE
Number of messages upper limmit

### ISSUE THREAD

**Issue by BasileiosKal** [decentralized-identity/bbs-signature#212]
Through the use of `expand_message` we put an upper limit to the number of signed messages.

`expand_message` aborts if `len_in_bytes` is larger than `2^16 - 1 = 65535`. In our case `len_in_bytes = count * expand_len`. The `count` can be (at most) equal to the number of signed messages (during ProofGen, if we decide to hide all messages). In the current ciphersuite `expand_len = 48`. As a result, the `count` can be at most 1365 which means that the total number of signed messages can also be at most 1365 (or at least a prover cannot choose to not disclose more than 1365 messages).

That's quite unfortunate IMO, since the 1365 messages limit seems quite small to me!

### How to solve this??

Not sure what the best solution is. The root of the problem is step 9 in [ProofGen](https://identity.foundation/bbs-signature/draft-looker-cfrg-bbs-signatures.html#name-proofgen), i.e., the step:
```
9. (m~_j1, ..., m~_jU) = hash_to_scalar(PRF(prf_len), U)
```
since U cannot be more than 1365. Should we call `hash_to_scalar` in a loop with multiple calls to the PRF or extent the output length of the PRF to get more seeds if we need more than 1365 scalars?? Or should we define expand_message alternatives with higher output limits (2^32 would be nice, however this would create more implementation barriers comparatively)??

**Comment by BasileiosKal** [comment]
Discussed on the last WG call. Will document the different options and revisit this after!

**Comment by christianpaquin** [comment]
As we discussed on the call today, perhaps good to measure the perf difference in practice after prototyping both approaches.

**Comment by BasileiosKal** [comment]
To track the conversation here, the currently discussed proposals are,
1. Call PRF in a loop.
2. Call `expand_message` in a loop and the PRF once.
3. Call both `expand_message` and the PRF in a loop.

The tradeoff (naturally) is between efficiency and simplicity. We also have to consider how testable  [ProofGen](https://identity.foundation/bbs-signature/draft-irtf-cfrg-bbs-signatures.html#name-proofgen) will be. In the 2nd option, the PRF is called once. This allows describing the output of the PRF on the ProofGen fixtures. On the 1st and 3rd proposals, the PRF is called in a loop, meaning that we have to use a "deterministic" PRF for the test vectors.

Bellow the different proposals are described in detail + their theoretical performance. Currently prototyping them, so hopefully will also post some benchmarking results soon.

**Note**: When it comes to security, none of them is constant time. However, side chanel attacks will have minimum impact since the number of loops is `O(U)`, where `U` is revealed in each proof.

## A. PRF in a loop
The simplest solution, creating each random scalar from a different pseudorandom seed. The bellow steps will be incorporated in ProofGen, in place of the current step 9.
```
// U: number of undisclosed messages
// prf_out_len = ceil(log2(r)/8)
1. for i in (1, ..., U):
2.     m~_i = hash_to_scalar(PRF(prf_out_len), 1)
```

## B. `expand_message` in a loop
This solution [proposed by  Riad Wahby](https://github.com/cfrg/draft-irtf-cfrg-hash-to-curve/issues/349) (who I thank again!!), uses `expand_message` in a loop with different DST's to guarantee independence. The proposal in the context of our spec is the following,

```
result = get_random_bytes(msg, len_in_bytes, dst)

Procedure:
1.  dst_next = I2OSP(0, 4) || dst
2.  random_bytes = ""

//  Get some random bytes
3.  numexp = floor(len_in_bytes / 65285)
4.  if numexp >= 2^32, ABORT
5.  for j in (1, ..., numexp):   // assumming that if numexp = 0 the loop will not run
6.     tmp = expand_message(msg, dst_next, 65535)
7.     random_bytes = random_bytes || tmp[0..65284]
8.     dst_next = I2OSP(j, 4) || tmp[65285..65535]

//  Get remaining random bytes (dst_next here MUST be the last one computed in the loop)
9.  tmp = expand_message(msg, dst_next, (len_in_bytes mod 65285))
10. random_bytes = random_bytes || tmp

11. return random_bytes[0..len_in_bytes]
```

Then, `hash_to_scalar` will be updated to call `get_random_bytes` instead of `expand_message`.

## C. `expand_message` and PRF in a loop
A combination of the above, using `hash_to_scalar` as a black box, for a "middle of the road" solution,

```
rand_scalars = get_random_scalars(PRF, count, dst)

Procedure:
1. scalars = []
2. max_count = floor(65535/expand_len)   // 1365 for our ciphersuites
3. ell = floor(count/max_count)
4. for i in (1, ..., ell):
5.     rand_scalars = hash_to_scalar(PRF(prf_out_len), max_count, dst)
6.     scalars.push(rand_scalars) // push all elements from rand_scalars to the scalars list 

// Get the remaining random scalars
7. rand_scalars = hash_to_scalar(PRF(prf_out_len), count mod max_count, dst)
8. return scalars.push(rand_scalars)
```

Then in the ProofGen we can just call
```
8. (1, r2, e~, r2~, r3~, s~, m~_1, ..., m~_U) = get_random_scalars(PRF, 6+U)
```


# Performance
I'm using hash function and PRF calls as an indicator of performance. The shown performance is for the "worst case" where we using `BLS12381-SHA256` ciphersuit, i.e., `expand_message_xmd` with SHA-256.
- Let `U` be the number of undisclosed messages. Let also for simplicity `U > 1365`.
- Let `ell = ceil(U * expand_len / hash_out_len) + 1` the number of hash invocations in `expand_message_xmd`

| Proposal | Hash invocations     | PRF calls     |
| -------- | -------------------- | ------------- |
|  A       |      3 * U    |   U   |
|  B       | O(floor(U/1360) * 2050 + 2042) |    1    |
|  C       | O(floor(U/1365) * 2050 + 2048) | ceil(U/1365) |

C seems like a good tradeoff IMO. It will make testing ProofGen harder though. However I'm not sure if the complexity of B is worth it. 

To make the difference more concrete here's some results for different U values.

|      U = 100    |                 | |
| -------- | ----------------------| --| 
| Proposal | Hash calls | PRF calls |
|  A       |  300      |  100     |
|  B       |  152      |  1        |
|  C       |  151      |  1        |

|     U = 2000     |                 | |
| -------- | ----------------------| --| 
| Proposal | Hash calls | PRF calls |
|  A       |  6000      |  2000     |
|  B       |  3012      |  1        |
|  C       |  3003      |  2        |

|    U = 4000      |                 | |
| -------- | ----------------------| --| 
| Proposal | Hash calls | PRF calls |
|  A       |  12000      |  4000     |
|  B       |  6022      |  1        |
|  C       |  6004      |  3        |

**Note**: The actual formulas for B and C are:
- for B: `floor(U*48/65285) * 2050 + ceil((U*48 mod 65284)/32) + 2`
- for C: `floor(U/1365) * 2050 + ceil(1.5 * (U mod 1365)) + 2`

**Comment by BasileiosKal** [comment]
Actually, there is another option. We can call PRF in a loop but we don't need to also use `expand_message`, we can just mod the output of the PRF, i.e., 
```
expand_len = ceil((ceil(log2(r))+k)/8)  // = 48 for the current ciphersuites
for i in (1, ..., U):
    m~_i = OS2IP(PRF(prf_out_len)) mod r
```
No hashes are needed for this solution. Maybe this is the best approach to keep things simple and efficient.
