### ISSUE TITLE
P1 calculation in tooling code

### ISSUE THREAD

**Issue by dev0x1** [decentralized-identity/bbs-signature#217]
As per spec, P1 is calculated using `create_generators` with a specific `generator_seed`. `create_generators` procedure as described [here](https://identity.foundation/bbs-signature/draft-looker-cfrg-bbs-signatures.html#name-generator-point-computation) starts calculation with `n=1` but below reference reference code in `tooling`  to calculate P1 uses `n=0`. 
https://github.com/decentralized-identity/bbs-signature/blob/3e69a8b16fd7788993e9d3a8849f311ade47fc5e/tooling/message-generators/src/main.rs#L193
I think the code should be updated as below and then the new values of `P1` also need to be updated in the cipher suites constants section.
```rust 
let extra = 1usize.to_be_bytes()[4..].to_vec();
```

**Comment by BasileiosKal** [comment]
Thanks for pointing this out! Addressed in #221.

**Comment by tmarkovski** [comment]
Actually, `usize` has variable length on different architectures, so using `u64` is a better option.
