### ISSUE TITLE
Public key format

### ISSUE THREAD

**Issue by BasileiosKal** [decentralized-identity/bbs-signature#219]
When using the public key as input to Sign, Verify etc., we can define it either as a point of G2 or as an octet string. Rn we do the later, consistent with what the BLS spec does.

That said, passing it as a G2 point, will simplify the encode for has operation a bit, since we don't need a "special clause" there so we would not append it with it length, since it would be handled like any other point. See also [here](https://github.com/decentralized-identity/bbs-signature/pull/216#discussion_r980354472) for context. 

IMO defining it as an octet string is more intuitive, but Im fine with both.

**Comment by tmarkovski** [comment]
Would it make sense to do the same for the secret key (instead "non negative integer mod r") and treat is as scalar, the same way the `messages` are?

**Comment by tplooker** [comment]
I'm in favour of keeping this as octet string based input.

**Comment by BasileiosKal** [comment]
Discussed on WG call on 20th of Mar. Related to #246 and #223. Closing in favor of those issues
