### ISSUE TITLE
Adding U in the proof value.

### ISSUE THREAD

**Issue by BasileiosKal** [decentralized-identity/bbs-signature#233]
Opening to track a [suggestion](https://github.com/decentralized-identity/bbs-signature/pull/230#discussion_r1046293817) made by @andrewwhitehead in PR #230.

The idea IMU is to add `U` (total number of undisclosed messages) in the proof, i.e.,

`proof = (A', Abar, D, c, e^, r2^, r3^, s^, *U*, (m^_1, ..., m^_U))`.

This will add some redundancy in case the proof gets accidentally truncated (or malformed in general).

**Comment by BasileiosKal** [comment]
Personally not sure how useful this will be above the transport layer however this would potentially make the suggestion in #227 easier to apply.

**Comment by tplooker** [comment]
I'm a -1 to this proposal for the following reasons

- It increases the proof size by 8 bytes
- The detection of truncation only works for malformed components beyond U in the proof value e.g `(m^_1, ..., m^_U)`
- For U to be useful in the proof, implementations that are decoding proofs would have to written a certain way to detect a malformed proof.

This issue does raise a good point that we could omit L from proof verify and deduce it based on length(m^_1, ..., m^_U) when decoding the proof.

**Comment by tmarkovski** [comment]
This was suggested at the start of this work item as well, as the previous implementations of BBS+ used this approach. In my mind, `U` is part of the public proof parameters along with the presentation header `ph`, and does not need to be encoded in the proof itself.

**Comment by BasileiosKal** [comment]
Discussed on the WG call 9th of January. Consensus is that rn the added redundancy is useful in some rare cases. Will discuss closing this issue in the next WG call, with the potential of reopening after #227 is resolved

**Comment by BasileiosKal** [comment]
Discussed in the WG call 23d of January. Closing the issue with the potential of reopening after #227. Will also look into adding an implementation note describing this solution as a potential mitigation if one is needed.

**Comment by Wind4Greg** [comment]
Like this. I was doing something like this in my code but deriving U from the L value.
