### ISSUE TITLE
Text representation

### ISSUE THREAD

**Issue by BasileiosKal** [decentralized-identity/bbs-signature#234]
Tracking issue for a [comment](https://github.com/decentralized-identity/bbs-signature/pull/230#discussion_r1047573733) made by @andrewwhitehead in #230.

In the draft we are referring to text as ASCII string. This is kinda confusing as often ASCII refers to the characters octet encoding rather than the characters themselves. Alternatives include: Text, String, Character sequences etc.

**Note**: the only place we actually use this terminology is for encoding the ciphersuite id and the DSTs. 

Some questions are: 
- do we want to disallow non-ASCII chars??
- do we want generic "string" encoding rules (i.e., as in #230) or we should just define the DSTs and ciphersuite id to be octet strings from the start (i.e., ASCII encoded strings). This is what the h2c and bls curve do AFAIK.

**Comment by OR13** [comment]
`U+1FAE0`

**Comment by tplooker** [comment]
+1 to the proposal to simplify the specification to state the octet representation of any strings rather than define complex string encoding rules

**Comment by BasileiosKal** [comment]
Discussed on WG call 9th of January. Next step is to open PR on this approach (use the octet representation of string rather than the strings).

**Comment by BasileiosKal** [comment]
Discussed on WG call 23d of January. Next step is to open PR with example.
