### ISSUE TITLE
Plain English section titles

### ISSUE THREAD

**Issue by andrewwhitehead** [decentralized-identity/bbs-signature#244]
This is a bit subjective, but I think we should adopt plain English titles for (sub)sections in the draft rather than using function names.

At the moment section 3 looks like this:

    3.1.  Parameters
    3.2.  Considerations
      3.2.1.  Subgroup Selection
      3.2.2.  Messages and generators
      3.2.3.  Serializing to octet strings
    3.3.  Key Generation Operations
      3.3.1.  KeyGen
      3.3.2.  SkToPk
    3.4.  Core Operations
      3.4.1.  Sign
      3.4.2.  Verify
      3.4.3.  ProofGen
      3.4.4.  ProofVerify

An updated version might look like this:

    3.1.  Parameters
    3.2.  Considerations
      3.2.1.  Subgroup Selection
      3.2.2.  Messages and generators
      3.2.3.  Serializing to octet strings
    3.3.  Key Generation Operations
      3.3.1.  Secret Key Generation
      3.3.2.  Public Key Calculation
    3.4.  Core Operations
      3.4.1.  Signing
      3.4.2.  Signature Verification
      3.4.3.  Proof Generation
      3.4.4.  Proof Verification

For comparison the [VOPRF draft](https://cfrg.github.io/draft-irtf-cfrg-voprf/draft-irtf-cfrg-voprf.html).

**Comment by tplooker** [comment]
Im supportive of this direction I think it improves the readability of the specification.

**Comment by BasileiosKal** [comment]
+1 from me as well! Will give it a go if that's ok Andrew.
