### ISSUE TITLE
Incorrect naming of the signature scheme used

### ISSUE THREAD

**Issue by MrM0nkey** [decentralized-identity/bbs-signature#249]
Hi there,

I am writing a paper describing an anonymous credential scheme that works with BBS+ signatures. Basically, I am migrate the DDA+ protocol from Camenisch, J., Drijvers, M., Lehmann, A. (2016). Anonymous Attestation Using the Strong Diffie Hellman Assumption Revisited on Anonymous Credentials. I plan to refer to the specification https://identity.foundation/bbs-signature/draft-irtf-cfrg-bbs-signatures.html. I noticed that you refer to BBS signatures in the specification, although you specify BBS+ signatures. Would it be possible to change the name from the BBS signature scheme to the BBS+ signature scheme and thus adjust other parts of the specification such as the introduction?

Best regards
Chris

**Comment by tplooker** [comment]
Hi @MrM0nkey, this question was raised and discussed by the WG early days, see #30. We elected to drop the + mainly for very practical reasons and don't plan to re-introduce it. Further clarification in the introduction may be added to make this association/decision more obvious.

**Comment by BasileiosKal** [comment]
Discussed on WG call 6th of Mar. Agreement is that for various practical reasons the WG call will not consider updating the name. See #30. Closing.

**Comment by MrM0nkey** [comment]
Hi @tplooker and @BasileiosKal, thanks for your quick response. I would definitely recommend that you be more explicit in the introduction about BBS+ and why you decided to omit the +. At the moment, your reference to BBS _"The name BBS is derived from the authors of the original academic work of Dan Boneh, Xavier Boyen and Hovav Shacham where the scheme was first described"_ is certainly misleading to uninformed readers.

Best regards
Chris
