### ISSUE TITLE
Variable and function naming

### ISSUE THREAD

**Issue by andrewwhitehead** [decentralized-identity/bbs-signature#25]
The current draft uses the caret and tilde characters in variable naming, as they are in some of the source research. This causes issues with the markdown format of the specification in that it is burdensome and/or impossible to properly escape these characters.

I don't see any clear standards on variable or function naming in other IETF drafts. Variables may be upper-, lower-, camel-, or snake-cased. Functions can be camel-cased, snake-cased, or kebab-case (ie. `HKDF-Extract`).

Some suggestions for discussion:

- name spec-internal variables and functions in snake case unless they represent an initialism (like `DST`) or are commonly capitalized (such as a field `F` or the set of integers `Z`). I think there is a tendency to use capitalized variables for elliptic curve points like `A` in the signature
- name external functions according to their respective standards when possible, for example `hash_to_curve`
- a trailing apostrophe is allowed in variable names, such as `s'` - precedent in hash-to-curve draft for example
- for variables currently using `~` as a suffix use `_b` short for blinding factor
- for variables currently using `^` as a suffix use `_c` short for commitment

**Comment by bumblefudge** [comment]
See #17

**Comment by andrewwhitehead** [comment]
I believe this has been resolved by other issues and PRs.
