### ISSUE TITLE
Unique fixture caseName

### ISSUE THREAD

**Issue by christianpaquin** [decentralized-identity/bbs-signature#252]
It would be desirable to use unique `caseName` values in the fixtures, to differentiate them while running them in unit test framworks. For example, "multi-message signature, all messages revealed proof" appears 11 times in the proof fixture files, and all the signature ones are either name "single" or "multi-message signature".

Update: I just realized that the spec uses different names for each test, but the fixtures doesn't update all of them (copy-paste leftover, I assume)

**Comment by BasileiosKal** [comment]
Discussed on WG call on 13th of Mar.

> It would be desirable to use unique `caseName`

I imagine this means unique per ciphersuite??

> Update: I just realized that the spec uses different names for each test, but the fixtures doesn't update all of them (copy-paste leftover, I assume)

Not sure i follow 100%?? Is there places in the document that should be populated by test vectors but are not??

**Comment by christianpaquin** [comment]
> I imagine this means unique per ciphersuite??

Yes.

> Not sure i follow 100%?? Is there places in the document that should be populated by test vectors but are not??

The spec is ok, but I'd suggest changing the `caseName` of the signature.json and proof.json files to match the corresponding files. Otherwise the test output looks like you are running the same test over and over again (e.g, for my lib):
```
  ✓ signature001: single message signature (417 ms)
  ✓ signature002: single message signature (191 ms)
  ✓ signature003: single message signature (191 ms)
  ✓ signature004: multi-message signature (664 ms)
  ✓ signature005: multi-message signature (502 ms)
  ✓ signature006: multi-message signature (508 ms)
  ✓ signature007: multi-message signature (406 ms)
  ✓ signature008: multi-message signature (354 ms)
  ✓ signature009: multi-message signature (428 ms)
  ✓ proof001: single message signature, message revealed proof (251 ms)
  ✓ proof002: multi-message signature, all messages revealed proof (399 ms)
  ✓ proof003: multi-message signature, multiple messages revealed proof (512 ms)
  ✓ proof004: multi-message signature, all messages revealed proof (373 ms)
  ✓ proof005: multi-message signature, all messages revealed proof (427 ms)
  ✓ proof006: multi-message signature, all messages revealed proof (423 ms)
  ✓ proof007: multi-message signature, all messages revealed proof (29 ms)
  ✓ proof008: multi-message signature, all messages revealed proof (20 ms)
  ✓ proof009: multi-message signature, all messages revealed proof (292 ms)
  ✓ proof010: multi-message signature, all messages revealed proof (311 ms)
  ✓ proof011: multi-message signature, all messages revealed proof (15 ms)
  ✓ proof012: multi-message signature, all messages revealed proof (342 ms)
  ✓ proof013: multi-message signature, all messages revealed proof (348 ms) 
```
So for signatures, sig001 is ok, I'd use "invalid single message signature (modified message)" for sig002, etc.

I could printout these descriptions by parsing the validity and reason (for non-valid tests), but that feels like a lot of trouble; I think it'd be nice for each case to have a different name (within a ciphersuite)
