### ISSUE TITLE
Add an application for plain multi-message signatures

### ISSUE THREAD

**Issue by andrewwhitehead** [decentralized-identity/bbs-signature#254]
At the moment we define [`MapMessageToScalarAsHash`](https://identity.foundation/bbs-signature/draft-irtf-cfrg-bbs-signatures.html#name-mapmessagetoscalarashash) without really linking it to anything, suggesting it as a good default for encoding messages. Instead, I suggest that we explicitly define a 'plain multi-message signature' application, requiring that all messages are UTF-8 strings, and using this encoding rule for each. It could have a simple header value identifying the application, for instance `BbsUtf8TextSignature2023` (the name needs work).

Implementations could also choose to support a simple API for this signature application, something like: `PlainMultiSign(SK, messages: [String])` and `PlainMultiVerify(Sig, PK, messages)`.

**Comment by BasileiosKal** [comment]
Not opposed to this, just to make sure i get it, you mean defining an API that will use the core operations?? To make it more explicit how `MapMessageToScalarAsHash` is to be used?? So something like what [bls-sigs](https://www.ietf.org/archive/id/draft-irtf-cfrg-bls-signature-05.html#name-api) or [h2c](https://www.ietf.org/archive/id/draft-irtf-cfrg-hash-to-curve-16.html#name-encoding-byte-strings-to-el) does?

**Comment by BasileiosKal** [comment]
Closing as completed through #282
