### ISSUE TITLE
BBS draft suggested corrections

### ISSUE THREAD

**Issue by Luckydd99** [decentralized-identity/bbs-signature#261]
I leave below some mistakes of this [draft](https://identity.foundation/bbs-signature/draft-irtf-cfrg-bbs-signatures.html):

- In section 7.5.3 the output signature which appears in the test vector is the one regarding the SHAKE variant of the BBS protocol instead of the SHA-256 one;
- in section 7.5.4.2 the output signature which appears in the test vector is the one regarding the SHAKE variant of the BBS protocol instead of the SHA-256 one;
- section 3.2.2 does no longer contain input messages (they can now be find in section 7.3);
- in section 7.2 there is a typo (BLS12-381-SHA-356 instead of SHA-256).

**Comment by BasileiosKal** [comment]
Thanks @Luckydd99 for the feedback 🙏  much appreciated!

> section 3.2.2 does no longer contain input messages (they can now be find in section 7.3);

Not sure I'm following his one? Section 3.2.2 is not supposed to include test vectors. Is the suggestion for a different title (like Message to scalar maybe)??

Everything else are addressed in PR #263

**Comment by Luckydd99** [comment]
> Not sure I'm following his one? Section 3.2.2 is not supposed to include test vectors. Is the suggestion for a different title (like Message to scalar maybe)??

The suggestion was referring to the fact that Section 7.4, Section 7.5, Appendix C.1 and Appendix C.2 always refer to messages contained in Section 3.2.2, which indeed does not contain any message.

**Comment by BasileiosKal** [comment]
Oh I see! Thanks! Fixed in the PR

**Comment by tplooker** [comment]
Fixed in #263
