### ISSUE TITLE
Andrew's comment

### ISSUE THREAD

**Issue by BasileiosKal** [decentralized-identity/bbs-signature#265]
Tracking Issue for @andrewwhitehead's comment in PR #257: 

Comment: https://github.com/decentralized-identity/bbs-signature/pull/257#pullrequestreview-1468296014

**Comment by BasileiosKal** [comment]
My own comments on this are; 

> In future I may want to suggest moving c to the end of the serialized proof so that it's easier to remove 

Not opposed to this, but this will affect how de serialization works.

> also tempted to reorder Abar before Bbar in the equation

You mean [here](https://github.com/decentralized-identity/bbs-signature/pull/257/files#diff-af5e5e8fae3b8177ffbea885a6a9b1623c4fb790bc8eeaeef38d92706b30d0d1R550) for `C`??

**Comment by andrewwhitehead** [comment]
> You mean [here](https://github.com/decentralized-identity/bbs-signature/pull/257/files#diff-af5e5e8fae3b8177ffbea885a6a9b1623c4fb790bc8eeaeef38d92706b30d0d1R550) for `C`??

Yep, just because it feels slightly inconsistent when outputting (Abar, Bbar..) in the next line.
