### ISSUE TITLE
Naming of the draft BBS vs BBS+

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/bbs-signature#30]
I propose we rename the draft to "The BBS Signature Scheme" and elect to drop the + from all mentions of BBS. Through appropriate citations of the academic work I think we can still achieve the right level of association to the schemes origins. The rationale for dropping the + is that in many visible places that character is not allowed (e.g naming repositories, naming packages and programming language syntax)

**Comment by quartzjer** [comment]
I definitely support this :+1:.

**Comment by tplooker** [comment]
Addressed in #32 there was only two minor inconsistencies in the draft already that have been addressed
