### ISSUE TITLE
Remove KeyGen definition

### ISSUE THREAD

**Issue by andrewwhitehead** [decentralized-identity/bbs-signature#31]
This may be defined as a property of the profile along with details of the pairing-friendly curve in use. For BLS curves it probably makes sense to reference the BLS Signatures IETF draft (hopefully that is getting an update?).

**Comment by tplooker** [comment]
For reference the draft is located here https://github.com/cfrg/draft-irtf-cfrg-pairing-friendly-curves

**Comment by tplooker** [comment]
In particular this section https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-bls-signature-04#section-2.3

**Comment by tplooker** [comment]
Depending on the outcome of #87 if this is merged then we can close this as the definition for key gen in the spec has diverged from BLS signatures

**Comment by tplooker** [comment]
Agree with @christianpaquin, to provide further context the spec is currently not clear that the exact KeyGen operation defined is not required by implementations and instead they are free to generate keys in other ways if they wish.

**Comment by tplooker** [comment]
Either a note at the top of this operations definition or shifting it to an appendix is likely the way we will resolve this

**Comment by tplooker** [comment]
I think given there are a couple of deviations from the BLS signature spec such as the salt keeping this definition in this spec feels like the most accomodating solution? If we agree can this issue be closed?

**Comment by tplooker** [comment]
@andrewwhitehead

**Comment by andrewwhitehead** [comment]
Yes, I think that's fine. We probably ought to reference the BLS signature draft since it's a straight copy.

**Comment by tplooker** [comment]
Closing this issue based on the consensus above, we can round back to appropriate referencing of prior art one these operation definitions have settled a little more
