### ISSUE TITLE
Supporting deterministic signatures

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/bbs-signature#43]
BBS Signatures as defined in academic literature are non-deterministic in nature. In general non-deterministic digital signatures can be difficult from an implementation perspective due to their dependency on a sound RNG. It causes complexities around confirming implementation correctness because the RNG often has to be mocked or seeded in a particular way. There is the potential to modify the signature construction in this draft to make signatures deterministic, @mikelodder7 could you share your proposal for this?

The main questions I think we as a WG should be asking are:
- Do we want deterministic signatures?
- Do we want to take on the scope of deterministic signatures in the current draft?
- Given we are deviating from academic literature, what security proofs do we need?

**Comment by mikelodder7** [comment]
My suggestion is this:

u512() is a function that converts 64 bytes as a 512-bit number.

For regular signing:

inputs: 
- base order `q`
- secret key `x`
- messages `mi,...,mn`

1. hasher = SHAKE256(x, mi, ..., mn)
2. e = uint512(hasher.read(64)) % q
3. s = uint512(hasher.read(64)) % q
4. finish as normal

For blind signing:
inputs:
- base order `q`
- secret key `x`
- known_messages `mi,...,mn`
- commitment `U`

1. hasher = SHAKE256(x, U, mi,...,mn)
2. e = uint512(hasher.read(64)) % q
3. s = uint512(hasher.read(64)) % q
4. finish as normal

**Comment by BasileiosKal** [comment]
I like this method, but a comment from [here](https://datatracker.ietf.org/doc/html/rfc6979#section-3.2) worries me, i.e., "Performing a simple modular reduction would induce biases that would be detrimental to signature security"

Is this something that we will have to also worry about?

**Comment by mikelodder7** [comment]
This method already addresses the bias by pulling double the bytes. See https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-hash-to-curve-13#section-5.1.

**Comment by mikelodder7** [comment]
The bias is something to be aware of, but this method handles it properly.

**Comment by mikelodder7** [comment]
FYI, this is how it should be done with a single signer context. Threshold signing should not be restricted to this since all sorts of attacks can happen with deterministic signing.

**Comment by tplooker** [comment]
Currently covered in #62

**Comment by tplooker** [comment]
Closing with the merging of #62, resolution was to include this, initial test vectors conforming to this approach have been added in #67
