### ISSUE TITLE
[Proposal] An interop profile document

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/bbs-signature#46]
Given the discussion in #8 around how the core bbs signature draft should relate to underlying cryptographic primitive selection, I wanted to propose an approach that may be inline with this emerging consensus.

Instead of mentioning in the core bbs signature draft anything around concrete curves or digest algorithms we could define a seperate document which is an opinionated "bbs signature profile" aimed at promoting interoperable implementations. The profile would also host test vectors to facilitate this process.

If this approach is accepted by the community then I would suggest we immediately start work on one profile that uses the following.
- BLS12-381 as the pairing friendly curve
- SHAKE256 as the digest algorithm

Alternatively if having multiple document is too complex we could elect to merge these, however we would need to be careful in how we structure the document.

**Comment by OR13** [comment]
I think ideally, you just name the algorithm and define it concretely for those parameters... a profile for their configuration seems a bit excessive to me.

I do think you should make it obvious how someone might replace either in your spec, but I don't think you need to take ownership of defining that generality for all of IETF.

**Comment by tplooker** [comment]
Ok so a counter proposal would be to generalize section 5 https://identity.foundation/bbs-signature/draft-bbs-signatures.html#name-overview which is currently empty to be more "profiles" with the definition of BLS12-381 under that alongside concrete test vectors?

**Comment by OR13** [comment]
Have a look at:

- https://www.rfc-editor.org/rfc/rfc9162.html

- https://datatracker.ietf.org/doc/html/rfc8812

for examples of registeringthings.

**Comment by tplooker** [comment]
This issue has been addressed in #47 and #60, with the general consensus being around defining the BLS12-381 ciphersuite/profile within the draft
