### ISSUE TITLE
Register algorithms for BBS signatures in JOSE and COSE IANA registry

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/bbs-signature#48]
As raised by @OR13 on a recent PR review we should consider the scope to register the relevant JOSE and COSE algs with the IANA registry as a part of the core draft.

**Comment by OR13** [comment]
Here is a good example to copy from: 

https://datatracker.ietf.org/doc/html/rfc8812

I would just do this in your spec the sooner these are registered with IANA, the sooner we can all be using this suite with confidence... I think its a huge mistake to build on this suite without doing this work...because you may find that your signature or key representations change out under you, and your interoperability is destroyed because you have not name for their former and newer serializations.

**Comment by mikelodder7** [comment]
As long as it doesn't lock implementors into only using JOSE/COSE

**Comment by tplooker** [comment]
Of course not, just defines how the scheme can be used in those data representations

**Comment by tplooker** [comment]
Its worth noting that the current standard JOSE and COSE forms do not support the style of cryptographic representation required by a protocol like BBS Signatures. However [JWP](https://github.com/json-web-proofs/json-web-proofs) is likely to define one that will, so the ability to register suitable algorithms in the IANA registry, in this draft, will likely be dependent on that drafts completion, alternatively another internet draft could be written after this to define the registration.

**Comment by tplooker** [comment]
Based on the perspective shared above I'm proposing we close this issue on the grounds that it is out of scope for the current drafts to make IANA registrations for specific data representation forms like JOSE and COSE, marking as pending-close on that basis.

**Comment by OR13** [comment]
@tplooker I mostly care about the `OKP`, `crv`, `alg` side of these registrations.... Are they going to be handled in a different IETF spec? if so, can we link to something before closing this, so future searchers know where to join in / help ?

**Comment by tplooker** [comment]
w.r.t BLS12-381 key representation [this draft](https://tplooker.github.io/draft-looker-cose-bls-key-representations/draft-looker-cose-bls-key-representations.html) is where the definitions for JOSE and COSE iana registrations are mastered.

w.r.t to the algorithmic registration for BBS in JWP (an extension of JOSE) refer to [here](https://json-web-proofs.github.io/json-web-proofs/draft-jmiller-json-proof-algorithms.txt). No current extension draft for usage of BBS in COSE exists yet.

**Comment by tplooker** [comment]
@OR13 does that help?

**Comment by OR13** [comment]
- (jwk) https://tplooker.github.io/draft-looker-cose-bls-key-representations/draft-looker-cose-bls-key-representations.html
- (alg) https://json-web-proofs.github.io/json-web-proofs/draft-jmiller-json-proof-algorithms.txt

good to close
