### ISSUE TITLE
Indexes and messages notation

### ISSUE THREAD

**Issue by BasileiosKal** [decentralized-identity/bbs-signature#54]
The spec makes heavy use of lists of messages and indexes. We need a consistent way to represent those.

**- Option 1**:
Represent indexes with a consisted format like `I_t`, `I_d` corresponding to the total and disclosed messages. Represent the messages with something like,

    (msg[i] for i in I_d)   // or I_t

As such `spkGen` for example will be,

    spkGen(spk, PK, I_t, I_d, (msg[i] for i in I_d), pm)

**- Option 2**:
Define that all signatures on `L` messages will use the `L` first generators. With that, instead of the indexes of all the signed messages we can pass just the `totalSignedMessages`. That will also allow for a solution like [here](https://github.com/decentralized-identity/bbs-signature/issues/10#issuecomment-1018041832) with

    spkGen(spk, PK, revealedMessages, totalSignedMessages, pm)

where `revealedMessages` is a map between index and message. The drawback here is that when creating commitments for blind signatures, the user will need to choose the `n` first generators, with `n = Total_Committed_Messages` (i.e., always follow the example flow from the [blind signatures spec](https://github.com/decentralized-identity/bbs-signature/blob/main/draft-blind-bbs-signatures.md)), which could be restrictive for some applications.

**- Option 3**:
A compination of both, i.e.,

    spkGen(spk, PK, Indexes, revealedMessages, pm)

where again `revealedMessages` is a map between index and message and `Indexes` the indexes of all the messages

**Comment by tplooker** [comment]
With the merge of #64 is there anything outstanding with this issue @BasileiosKal? or can we close this?

**Comment by BasileiosKal** [comment]
Yeap. Further discussions on generators and indexes is better to be held elsewhere (like #68). Closing.
