### ISSUE TITLE
Test vectors

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/bbs-signature#7]
In order to facilitate interoperability this specification should contain a set of test vectors for the cryptographic structures defined

**Comment by tplooker** [comment]
Initial test vectors for the signature have been contributed in #67, the remaining will be contributed once the proof serialization is settled.

**Comment by tmarkovski** [comment]
Will be fixed with #221

**Comment by tplooker** [comment]
Adding a couple of comments here raised from #221 

- Form of messages in the test vectors is unclear, you must map these to scalar first as they are raw byte strings
- Disclosed message syntax for uses a zero based index which isn't described, other option is to use a 1 based counter as suggested by @christianpaquin

**Comment by tplooker** [comment]
The residual work here is to add test vectors for the proof protocol.
