### ISSUE TITLE
Define the hash_to_curve operation using SHAKE-256 XOF for BLS12-381 ciphersuite

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/bbs-signature#80]
Currently the [latest hash to curve draft](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-hash-to-curve-14) only defines [suites](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-hash-to-curve-14#section-8.8) for the BLS12-381. However due to the efficiencies involved in using SHAKE-256 we need to define the suite within this spec.

**Comment by BasileiosKal** [comment]
Not really clear to me what the efficiencies are. SHAKE-256 doesn't seem to have a clear advantage over SHA256 from [here](http://bench.cr.yp.to/results-hash.html#amd64-skylake) and [here](https://keccak.team/sw_performance.html).  @mikelodder7 is the intent to use the faster KangarooTwelve(which is not standardized if I'm not mistaken) or the ParallelHashXOF256?? Also why not use ParallelHash256 if thats the case (do we need an XOF for hash2curve??).

**Comment by mikelodder7** [comment]
We’re using shake in other areas of the code and it is faster when used in hash to curve. Hash to curve requires multiple calls to sha256 vs one to shake

**Comment by BasileiosKal** [comment]
That clears it up! Thanks! I'm curious as to why since that is the case, the spec opts for use of expand_message_xmd with sha256 instead of expand_message_xof with shake256 when it comes to bls12-381.

**Comment by tplooker** [comment]
> That clears it up! Thanks! That helped a lot to clarify it! I'm curious as to why since that is the case, the spec opts for use of expand_message_xmd with sha256 instead of expand_message_xof with shake256 when it comes to bls12-381.

Likewise, this was not immediately clear to me either especially considering other hash_to_curve suites elect to use SHAKE-256 defined in the draft.

**Comment by tplooker** [comment]
Addressed in #81
