### ISSUE TITLE
Element encoding when passed to HASH or XOF.

### ISSUE THREAD

**Issue by BasileiosKal** [decentralized-identity/bbs-signature#96]
See discussion in PR #95

In the spec, we need a way to pass elements of different types (EC points, integers, scalars etc) to a hash function. In that case, the encoding of those elements becomes important. IMO there are two options:
1. Explicitly making the transformation to octets for each hashed element. That would look something like
```
HASH(point_to_octets(PK), I2OSP(L), point_to_octets(H_1),..., point_to_octets(H_L),...)
```
2. Implicitly make the conversion (in the definition of the HASH for example or in a separate section etc.). This would look something like,
```
HASH(PK, L, H_1,..., H_L,... )
``` 
Personally I prefer 2. This would mean that we can also specify rules like the one Tobias pointed out [here ](https://github.com/decentralized-identity/bbs-signature/pull/95#discussion_r847082901)i.e., that each element should also be appended with its length, which i agree with. A consideration here is if we need to specify this rule for every element (even the point_to_octets outputs) or it is sufficient to specify it for general octet strings and non-negative integers (lengths of lists)??. IMO the latter will suffice, since there is not really any ubiquities that come to mind regarding the output of point_to_octets (which is also an octet string but with well defined length), but i could be mistaken.

**Comment by BasileiosKal** [comment]
2 additional notes:

1. To @tplooker  [point](https://github.com/decentralized-identity/bbs-signature/pull/97#discussion_r847895296), making the points in G1 or G2 be prepended with their length optional swifts the weight to the cipher suite to describe when this will hold for interoperability. As a result IMO we should either make this a requirement or remove it entirely (i vote for the later, since the length of the `points_to_octets` output can be defined by its value).

2. An additional consideration is whether we need to also prepend the lengths of lists to be hashed, to the list them serfs (for example the list of generators, or in the list of disclosed messages etc.)

**Comment by tplooker** [comment]
@BasileiosKal can you confirm with the merging of #97 whether we can now close this issue?

**Comment by BasileiosKal** [comment]
Yeap! Closing
