### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by alessandroguggino** [decentralized-identity/bbs-signature#99]
Good morning everyone,

I'm a Computer Engineering master's student working on my thesis which makes use of BBS signatures.
I would like to contribute to the repository since I think I have some suggestions and corrections, especially for the Blind Signature draft. (but maybe I could be wrong)

How am I supposed to do it? I have not found any guidelines, should I just do the work and then open a pull request?

Thank you for reading this and for your work, I really appreciate it!

**Comment by tmarkovski** [comment]
@alessandroguggino The best way would be to start a discussion as an issue here and describe your thoughts. If there are any changes to the computations, you can reference those and the team will respond. Once the problem and solution have been identified, you can submit an update in the form of a Pull Request.

**Comment by paulgrehan** [comment]
Hi @alessandroguggino - you can also sign up under a feedback agreement to be able to contribute given your student status, here's the link https://identity.foundation/join/#individual or reach out to us at membership@identity.foundation and we'll help get you started !

**Comment by alessandroguggino** [comment]
Thank you!
@paulgrehan Sorry, so should I join the foundation to contribute (= discuss and submit updates as pull requests) to this repository? Since there are legal implications, I would like to understand them a bit more before doing it.

**Comment by paul-yellowpink** [comment]
Hi @alessandroguggino - sorry for the delay in responding, for yourself and the group to get the most out of your participation it would be advantageous (chat in slack, join calls rather than an "arms length" iterative approach via PRs). It's not onerus for a student, if you are employed then it may require a contributor agreement however. If you could send an email to membership@identity.foundation I can cover in more detail :)

**Comment by paulgrehan** [comment]
Sorry - logged in with my other account - still me ;)

**Comment by alessandroguggino** [comment]
Thank you again!
I think we can close this issue then :)
